# Generated by Django 2.0 on 2017-12-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Naame', models.CharField(max_length=12)),
                ('First_Name', models.CharField(max_length=16)),
                ('Last_Name', models.CharField(max_length=16)),
                ('Gender', models.CharField(choices=[('Mr', 'Male'), ('Mrs', 'Female'), ('Seco', 'Gay')], default='Mr', max_length=4)),
                ('birthDay', models.DateField(default='07/07/1977')),
                ('Email', models.EmailField(max_length=128)),
            ],
        ),
    ]
