# Generated by Django 2.0 on 2017-12-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='User_Naame',
            new_name='User_Name',
        ),
    ]
