# Generated by Django 2.0 on 2017-12-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171221_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='member',
        ),
    ]
