# Generated by Django 2.0 on 2017-12-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20171221_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Memebership_type',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
