# Generated by Django 2.0 on 2017-12-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_memebership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Memebership_type',
            field=models.CharField(choices=[('S', 'Single'), ('F', 'Family')], default='S', max_length=1),
        ),
    ]
