# Generated by Django 2.0 on 2017-12-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
        ('members', '0008_auto_20171224_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='place',
            field=models.ForeignKey(default=1, on_delete=None, to='establishment.establishment'),
        ),
    ]
