# Generated by Django 2.0 on 2017-12-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, unique=True)),
                ('Establishment_type', models.CharField(choices=[('Hotel', 'Hotel'), ('SPA', 'SPA'), ('Resort', 'Resort'), ('Golf Clube', 'Golf Clube'), ('Country Club', 'Country Club'), ('Multi Service', 'Multi Service')], max_length=13)),
                ('Stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('Adress', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=13)),
                ('Web_Adress', models.URLField(max_length=32, null=True)),
                ('Email', models.EmailField(max_length=36)),
                ('Main_Photo', models.ImageField(null=True, upload_to='company_images')),
                ('About', models.TextField(max_length=256, null=True)),
                ('Logo', models.ImageField(null=True, upload_to='logos')),
            ],
        ),
    ]
